### ISSUE TITLE
erro on relashioship

### ISSUE THREAD

**Issue by joefreire** [rafwell/laravel-simplegrid#2]
$model = OrdemServico::with('tipo_servico', 'user_id');

        $Grid = new Grid($model, 'ordem_servico');

        $Grid->fields([
          'data'=>'Data Abertura',
          'tipo_servico'=>'Solicitante',
          'user_id'=>'tipo_servico',
          ]);

        return view('ordem.browse', ['grid'=>$Grid]);

Method Illuminate\View\View::__toString() must not throw an exception

**Comment by rafwell** [comment]
Hi Joe, we not support Eloquent relationships. You must change your code to like that:
```
 $model = OrdemServico::join('tipos_servicos','fk1','=','fk2')
    ->join('users',...)

    $Grid = new Grid($model, 'ordem_servico');

    $Grid->fields([
      'ordens_servicos.data'=>'Data Abertura',
      'tipos_servicos.tipo_servico'=>'Solicitante',
      'ordens_servicos.user_id'=>'Usuário',
      ]);

    return view('ordem.browse', ['grid'=>$Grid]);
```

**Comment by joefreire** [comment]
When i use that way the name go to wrong field

ex:
        $eventos = Evento::join('tipo_evento', 'tipo_evento.id','=','eventos.tipo_evento')
        ->select('tipo_evento.nome', 'eventos.id', 'eventos.nome');

        $Grid = new Grid($eventos, 'Eventos');
        
        $Grid->fields([
            'eventos.nome'=>'Evento',
            'data_inicio'=>'Data',
            'tipo_evento.nome'=>'Tipo',
            ]);

the eventos.nome and tipo_evento.nome show as same on grid

**Comment by rafwell** [comment]
I have not yet tested it to see if it's really a bug, but you can solve it now in two ways:

1. You can create an alias for the field that exists in two tables.
```
$eventos = Evento::join('tipo_evento', 'tipo_evento.id','=','eventos.tipo_evento')
->selectRaw('tipo_evento.nome, eventos.id, eventos.nome as evento_nome');

$Grid->fields([
        'eventos.nome'=>'Evento',
        'data_inicio'=>'Data',
        'evento_nome'=>'Tipo',
        ]);
```

2. You can use a virtual field to work around the problem.

```
$Grid->fields([
        'eventos.nome'=>[
         'label'=>'Evento',
         'field'=>'eventos.nome'
        ],
        'data_inicio'=>'Data',
        'evento_nome'=>[
          'label'=>'Tipo',
          'field'=>'tipo_evento.nome'
        ],
        ]);
```

If I can confirm it is a bug I will post a correction soon.

**Comment by rafwell** [comment]
The problem can be solved with ways above. After the release 1.5.0 we have a exception when detect double aliases.
