### ISSUE TITLE
Dúvida no funcionamento

### ISSUE THREAD

**Issue by leozoccoli** [rafwell/laravel-simplegrid#3]
Boa tarde Rafwell, muito bom o seu código, é disso que estou precisando para agilizar meus projetos. 
Porém não estou conseguindo fazer funcionar, sou novo com o framework laravel e talvez seja isso a minha dificuldade. 
Segui os passos descritos na página inicial, mas quando rodo minha página dá erro de:
 Class 'Rafwell\Grid\Grid' not found
Se puder me ajudar nessa configuração ficaria muito grato.  podemos nos falar por skype se assim preferir.

Desde já agradeço sua atenção. 
Obrigado.

**Comment by rafwell** [comment]
Oi @leozoccoli. Você está usando o código da versão 1, sendo que este é o repositório da versão 2. A classe que vocè deve utilizar na versão 2 é ```Rafwell\Simplegrid\Grid```, o código também é em inglês. Leia o [Read me](https://github.com/rafwell/laravel-simplegrid/blob/master/README.md) para ver o que precisa mudar no seu código.

**Comment by leozoccoli** [comment]
Obrigado @rafwell realmente era só isso. Agora queria ver com você outras duas coisas. 
1º minha grid mesmo com o css e font-awesome os icones não aparecem, e nem a ordenação funciona.
2º tambem gostaria de saber como coloco no ->action('edit', 'pasta') ao invés do nome Edit colocar o icone do lápis i class="fa fa-pencil-square-o" aria-hidden="true"
Obrigado pela ajuda.

**Comment by rafwell** [comment]
1º veja se você adicionou o css(do grid e do fontawesome) e o js do grid.
2º tente assim: 
```
->action('Editar', 'seulink', [
'onlyIcon'=>true,
'icon'=>'fa fa-folder'
])
```

**Comment by leozoccoli** [comment]
@rafwell fiz conforme falou mas sem sucesso. O icone não aparece e mesmo com o css e js adicionado não está dando certo. 
Se não se importar poderiamos fazer uma video pelo skype? Me ajudaria muito tirar essa duvida com você. 
Aproveitaria para ver se na função dos botões conseguiria colocar o MODAL para edição dos dados.
Skype: leonardozoccoli

**Comment by rafwell** [comment]
Vamos tentar continuar por aqui mesmo, pois a sua dúvida pode ser a mesma de outra pessoa. Se não os ícones não estão aparecendo é porque o css não foi aplicado corretamente.

Se você já adicionou os links do css e do js ao seu código, pode ter esquecido de publicar os arquivos com o comando `php artisan vendor:publish`. Se após a publicação não funcionar, veja no console do seu browser (F12) se tem algum erro e envie aqui.

**Comment by rafwell** [comment]
Se o problema persistir entre em contato.
