### ISSUE TITLE
Custom View

### ISSUE THREAD

**Issue by AlexMcowkin** [rafwell/laravel-simplegrid#4]
Hello!
thank you for your extension.
Tell me please how I can customize your template view?

Can you update your extension for that?

**Comment by rafwell** [comment]
Hello Alex, you're welcome.

I did not intend to allow changes to the template. This is a problem for version updates. What exactly would you like to change? Maybe it can be done without changing the template at the level of your project.

Of course, you can also make a fork and modify my views if you need them urgently.

**Comment by rafwell** [comment]
Closed due inactivity
