### ISSUE TITLE
php artisan vendor:publish doesnt copy files

### ISSUE THREAD

**Issue by AlexMcowkin** [rafwell/laravel-simplegrid#5]
Hi
Look.

this command doesnt make copy of config file and scripts:
`php artisan vendor:publish --provider="Rafwell\Simplegrid\SimplegridServiceProvider"`

can you check please?

I did it manually

**Comment by rafwell** [comment]
Hi, looks good. Certify if u have added in config/app.php our service provider before run this command.

**Comment by rafwell** [comment]
Clo

**Comment by rafwell** [comment]
Closed due inactivity.
