### ISSUE TITLE
Problemas no Icone

### ISSUE THREAD

**Issue by helesjunior** [rafwell/laravel-simplegrid#6]
Olá rafwell,

Encontrei um erro com ícones nas actions. No arquivo grid.blade.php vc informa $action['icone'] e este o correto seria $action['icon']

Muito boa sua grid.

Abraços

**Comment by rafwell** [comment]
Obrigado @helesjunior .
Problema resolvido na versão 1.8.1.

https://github.com/rafwell/laravel-simplegrid/commit/c9955328470b08135c1356f20dd1395af49ad0d7
