### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by Loirto** [rafwell/laravel-simplegrid#7]
It's not working on PHP 7.4

PHP 7.4.3 (cli) (built: Feb 18 2020 17:29:46) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

I got an error on **vendor\rafwell\laravel-simplegrid\src\Query\DefaultQueryBuilder.php:111**

 ErrorException
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

**Comment by rafwell** [comment]
Hi. Fixed on https://github.com/rafwell/laravel-simplegrid/commit/185de34e11ead67e0b941b3af983f9e66730aef2. Try update to version 1.17.1

**Comment by Loirto** [comment]
It's working now!!!!

Just for your information, I have this two warnings (they are not new, the old version had it too):

Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.

Thank you!

**Comment by rafwell** [comment]
@Loirto  about these warnings, thats not our package dependencies. You must fix that by yourself. Probably you only need update your composer.json to use the new packages instead of the abandoned packages.

Good luck!
