### ISSUE TITLE
Demo page offline

### ISSUE THREAD

**Issue by RicLzPt** [rafwell/laravel-simplegrid#8]
Demo page is offline

**Comment by rafwell** [comment]
Hi. Thank you for this alert. I've tried to up the demo again, but maintaining this takes a long time, the heroku free plan refresh the database sometimes, so I need reread the documentation to remember how use the client, restore a dump reconfigure... unfortunately I don't have time to do this, so I'm removing the demo page from the docs.

I sorry for that.
